urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required
from .views import PostDetail, PostList, PostShare, Admin_Post_Preview

app_name = 'blog'
urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^share/(?P<post_id>\d+)/$', PostShare.as_view(), name='post_share'),
    url(r'^admin/post/(?P<post_id>\d+)/$', staff_member_required(Admin_Post_Preview.as_view()), name='admin_post_preview'),
    ]

models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from baseapp.models import Recently
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(Recently):
    STATUS_CHOICE = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    )
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
    image = models.ImageField(upload_to='post/%Y/%m/%d', blank=True)
    image_description = models.CharField(max_length=60)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # The Dahl-specific manager.

    class Meta:
        ordering = ('-publish',)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug,
                                                 ])

class Comment(Recently):
    mail = models.EmailField()
    pseudo = models.CharField(max_length=30)
    body = models.TextField()
    post = models.ForeignKey('Post',
        on_delete=models.CASCADE,
        blank=False,
        related_name='comments')


    def __str__(self):
        return 'Commented by {} in {}'.format(self.pseudo, self.post)

forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['pseudo', 'mail', 'body']

views.py
from django.http import HttpResponse, QueryDict
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post, Comment
from baseapp.models import Application
from django.core.mail import send_mail
from .forms import CommentPostForm, EmailPostForm
from baseapp.views import FieldsView

# Create your views here.
class PostList(FieldsView):
    """
        list the posts
    """

    def get(self, request):
        posts = Post.published.all()
        applications = Application.objects.all()

        # Pagination
        paginator = Paginator(posts, 5)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        context = {'posts': posts,
                   'page': page,
                   'fields': self.fields,
                   }

        return render(request, 'blog/post/list.html', context)


class PostDetail(FieldsView):
    """
        Detail of post
    """
    applications = Application.objects.all()

    def get(self, request, year, month, day, post):
        post = get_object_or_404(Post, slug=post,
                                       status='published',
                                       publish__year=year,
                                       publish__month=month,
                                       publish__day=day)

        try:
            comments = Comment.objects.all().filter(post=post.id)
        except:
            pass

        comment_form = CommentPostForm()

        context = {
                    'post': post,
                    'fields': self.fields,
                    'comments': comments,
                    'comment_form': comment_form
                    }

        return render(request, 'blog/post/detail.html', context)


    def post(self, request, year, month, day, post):

        post = get_object_or_404(Post, slug=post,
                                       status='published',
                                       publish__year=year,
                                       publish__month=month,
                                       publish__day=day)
        try:
            comments = Comment.objects.all().filter(post=post.id)
        except:
            pass

        comment_form = CommentPostForm(request.POST)

        if comment_form.is_valid():
            try:
                cf_cleaned = comment_form.cleaned_data
                print(cf_cleaned)
                insert_db = Comment.objects.create(pseudo=cf_cleaned['pseudo'], mail=cf_cleaned['mail'], body=cf_cleaned['body'], post_id=post.id)
                insert_db.save()
                comment_form = CommentPostForm()
            except Exception as e:
                flag = "Exception while processing. (%s)" % e




        context = {'post': post,
                   'fields': self.fields,
                   'comments': comments,
                   'comment_form': comment_form
                   }

        return render(request, 'blog/post/detail.html', context)



class PostShare(FieldsView):
    sent = False
    applications = Application.objects.all()

    def get(self, request, post_id):
        form = EmailPostForm()
        post = get_object_or_404(Post, id=post_id, status='published')


        context = {'post': post,
                   'fields': self.fields,
                   'form': form,
                   'sent': self.sent}

        return render(request, 'blog/post/share.html', context)

    def post(self, request, post_id):
        form = EmailPostForm(request.POST)
        post = get_object_or_404(Post, id=post_id, status='published')
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], self.post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'youradress.mail@host.com', [cd['to']])
            self.sent = True

        context = {'post': post,
                   'form': form,
                   'fields': self.fields,
                   'sent': self.sent
                   }
        return render(request, 'blog/post/share.html', context)

class Admin_Post_Preview(FieldsView):

    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        return render(request, 'admin/blog/preview.html', {'post': post})

templates/blog/base.html
{% extends 'baseapp/base.html' %}
{% load static %}

{% block header%}
{% include "baseapp/head.html" %}
{% endblock %}

{% block content %}
{% endblock %}

templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="grid-container">

  <h1 class="text-center">{{ post.title }}</h1>
  {% if post.image %}
  <img src="{{ post.image.url }}" alt="{{ post.image_description }}">
  {% endif %}
  <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
  <p>{{ post.body|linebreaks }}</p>
  <p><a href="{% url "blog:post_share" post.id %}">Share this post </a></p>

  <h2>Similar posts</h2>

  {% for post in similar_posts %}
     <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
  {% empty %}
     There are no similar posts yet.
  {% endfor %}
  {% with comments.count as total_comments %}
     <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
  {% endwith %}

   {% for comment in comments %}
       <div class="comment">
           <p class="info">Comment {{ forloop.counter }} by {{ comment.pseudo }}</p>
           <p>{{ comment.created }}</p>
           {{ comment.body|linebreaks }}
           <hr>
       </div>
   {% empty %}
       <p>There are no comments yet.</p>
   {% endfor %}

   {% if new_comment %}
       <h2>Your comment has been added.</h2>
   {% else %}
   <div class="grid-x grid-padding-x">
  <div class="medium-6 cell">
       <h2>Add a new comment</h2>
       <form action="." method="post" id="formcommentpost">
           {{ comment_form.as_p }}
           {% csrf_token %}
           <button class="button large expanded" type="submit" form="formcommentpost" value="send e-mail">Add comment</button>
       </form>
    </div>
  </div>
   {%  endif %}
</div>
{% endblock %}

templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="grid-container">

  <h1 class="text-center">My Blog</h1>

  {% for post in posts %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.image_description }}">
    {% endif %}
    <p class="small-text-left">Publied {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}

</div>

{% include "baseapp/pagination.html" %}

{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="grid-container">
  {% if sent %}
    <h1></h1>
    <p>"{{ post.title }}" was succefully sent by e-mail</p>
  {% else %}
   <h1>Share "{{ post.title }}" by e-mail</h1>
   <form action="." method="post" id="formsharepost">
     {{ form.as_p }}
     {% csrf_token %}
    <button class="button large expanded" type="submit" form="formsharepost" value="send e-mail">send e-mail</button>
  </form>
  {% endif %}
</div>
{% endblock %}